"""add age

Revision ID: dd1327e82da1
Revises: d21fd481d74b
Create Date: 2023-11-14 18:13:54.756602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1327e82da1'
down_revision: Union[str, None] = 'd21fd481d74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Character', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Character', 'age')
    # ### end Alembic commands ###
