"""change description

Revision ID: ed55243aa27b
Revises: 54426ffa5324
Create Date: 2023-11-15 21:25:21.735939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed55243aa27b'
down_revision: Union[str, None] = '54426ffa5324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Character_id', table_name='Character')
    op.drop_table('Character')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Character',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Character_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resourceURI', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Character_pkey')
    )
    op.create_index('ix_Character_id', 'Character', ['id'], unique=False)
    # ### end Alembic commands ###
